permalink: /:year/:month/:title.html

exclude: [".rvmrc", ".rbenv-version", "README", "Rakefile", "changelog.md", "sass_converter.rb", "Gemfile", "Gemfile.lock", ".tm_properties", "config.rb", "sass", "CNAME"]

baseurl: dhuny.com

title : thanks i could help, bro
tagline: wub
author :
  name : Rey Dhuny
